###
### collection of functions used by multiple files in this project
###

library(tm)
library(magrittr)
library(ggplot2)

tfidf_tm <- function(corpus, sparsity = 0.992){
    # Calculate normalized tfidf matrix of a coupus using tm package
    #
    # Arguments:
    #   corpus: a vector of text documents
    #   sparsity: fraction of top words to keep
    #
    # Return:
    #   matrix, each row is the mormalized tfidf vector of a document
    
    corpus <- Corpus(VectorSource(corpus)) %>%
        tm_map(tolower) %>%
        tm_map(stripWhitespace) %>%
        # remove stopwords before removing punctuationo so that stopwords like 
        # it's and i'll can be removed
        tm_map(removeWords, stopwords("english")) %>%
        tm_map(removePunctuation) %>%
        tm_map(stemDocument)
    
    tfidf <- DocumentTermMatrix(
        corpus,
        control = list(weighting = function(x) weightTfIdf(x, normalize = FALSE))
    ) %>%
        removeSparseTerms(sparsity) %>%
        as.matrix() 
    
    # normalize so that each row vector has length of 1
    tfidf <- tfidf / sqrt(rowSums(tfidf * tfidf))
    
    return(tfidf)
}


plot_cv <- function(rep_id = NULL, dat = metrics_cv){
    # Plot the train and validation metrics over iterations of 
    # cross validation that used to find best parameters
    #
    # Arguments:
    #  rep_id: one of the many repeats. If NULL, plot each repeat
    #  dat: list of data frames generated by the cross validation run
    
    if (is.null(rep_id)){
        for (i in 1:length(dat)){
            p <- ggplot(dat[[i]]) +
                geom_line(aes(iter, train_mean), color = "blue") +
                geom_line(aes(iter, test_mean), color = "red") +
                labs(title = paste("repeat", i),
                     x = "Iteration / Epoch",
                     y = "Average Metrics")
            print(p)
            
            key <- readline(
                prompt = paste0("Press [Enter] to view next repeat", 
                                " [Esc] to exit: ")
            )
        }
    } else {
        ggplot(dat[[rep_id]]) +
            geom_line(aes(iter, train_mean), color = "blue") +
            geom_line(aes(iter, test_mean), color = "red") +
            labs(title = paste(rep_id, "repeat"),
                 x = "Iteration / Epoch",
                 y = "Average Metrics")
    }
}


metrics_binary <- function(y_true, y_pred, cutoff = 0.5){
    # Get key metrics of binary classification
    y_pred_class <- round(y_pred)
    auc <- ModelMetrics::auc(y_true, y_pred)
    f1 <- ModelMetrics::f1Score(y_true, y_pred, cutoff)
    sensitivity <- ModelMetrics::sensitivity(y_true, y_pred, cutoff)
    specificity <- ModelMetrics::specificity(y_true, y_pred, cutoff)
    
    cat("confusion matrix:\n       y_true\n")
    print(ModelMetrics::confusionMatrix(y_true, y_pred))
    cat("   \n")
    
    return(c(auc = auc, f1 = f1, sensitivity = sensitivity, specificity = specificity))
}
