---
title: " "
---

### Sample Type / Medical Specialty
The website [mtsamples.com](https://www.mtsamples.com/) has a collection of 4999 clinical notes provided by its users. These clinical notes have been confirmed by experts to be of the quality of the real clinical notes. They have been categorized into 40 sample types / medical specialties. Most of the categories are distinct medical specialties dealing with unique organ systems, such as cardiovascular / pulmonary,  gastroenterology and urology. Some categories cover more broad topics such as consult - history and phy., radiology, surgery, and discharge summary. 

We scraped all notes for further analysis. The first thing we notice is that most clinical notes appear in two or more categories. There are 1742 samples in two categories, 389 in three categories, 33 in four, and 1 in five. Only 221 have no duplicates. Most duplications are caused by sample types like "Consult - History and Phy.", "Discharge Summary", "Radiology", "SOAP / Chart / Progress Notes", and "Surgery", which are expected to ovelap with true medical specialties. The specialties with most notes are  "Gastroenterology", "Obstetrics / Gynecology", "Cardiovascular / Pulmonary", "Neurology", "Urology", and "Orthopedic", each having more than 100 notes. Duplication among them is much less severe; we will have 1402 non-duplicated samples out of 1498.

### Section headers
As mentioned previously, the names of section headers varies from notes to notes. From the 4999 clinical notes, we found 1910 unique headers. Most of them are rare, only appearing in a few of clinical notes: 230 in one notes, 773 in two notes, 200 in three notes, and 84% of them in less than ten notes. 

There is no single section header appears in the majority of clinical notes. The most popular section header ANESTHESIA appears in 27.5% of notes. The lack of dominance, however, does not suggest that the content of clinical notes lack a consistent theme. It is more likely because of how the sections are named. For example, the combined sections " PREOPERATIVE DIAGNOSIS" and "PREOPERATIVE DIAGNOSES" score 35%, and obviously they should be the same. Actually there are 72 unique section headers containing "DIAGNOSIS" or "DIAGNOSES". Even worse, 154 unique section headers contain "HISTORY". If the naming of section headers is consistent, we will see popular headers appearing in most clinical notes. Considering current status, a lot of work is needed to clean this mess up. 

 
