---
title: " "
---

Clinical notes compiles text from a number of sources, including patients' own description of symptoms, answers to the nurse's or doctor's questions, doctor's diagnosis, physical exams, lab reports, radiology reports, and discharge summaries. A typical note may cover the reasons for the hospitalization, significant findings, procedures, treatments, medications, patient conditions at discharge, and patient and caregiver instructions.

Clinical notes can be mined for potential [applications](https://www.hindawi.com/journals/jhe/2018/4302425/#B34) in medical decision support, disease risk prediction,  mobile health, network medical treatment, personalized healthcare, disease evolution prediction and drug reaction detection. There have been researches try to predict [readmission risk](https://arxiv.org/abs/1711.10663), [clinical intervention](https://arxiv.org/abs/1705.08498), [early psychiatric readmission ](https://www.nature.com/articles/tp2015182.pdf), [adverse Drug Events](https://www.aclweb.org/anthology/W15-2620.pdf), and [chronic diseases](https://arxiv.org/abs/1808.04928) using clinical notes. Clinical note can also be used to [link social, behavioral, and cultural factors to health and disease outcomes](https://www.ncbi.nlm.nih.gov/pubmed/25717417) and  [derive medical code](https://www.aclweb.org/anthology/N18-1100/).

Ideally, a clinical note is divided into multiple sections to account for the diverse contents; common sections include chief complaint, history of present illness, diagnosis, procedures, medications, and discharge disposition etc. Knowing the section a word belongs to is imperative to understanding the meaning of the word. For example, a drug name in section medication means the patient was taking the drug, while in section allergy indicates the patient did not take the drug. 

In reality, however, healthcare providers structure the clinical notes in their own ways and often use different section headers for the same contents. This arbitrary naming of section headers adds more difficulty to the already complicated analysis of unstructured clinical notes.

Another obstacle is the limited access to clinical notes, as the use of protected heath information (PHI) is regulated by Health Insurance Portability and Accountability Act (HIPAA) in the United States. Public datasets such as [MIMIC-III](https://mimic.physionet.org/) and [i2b2 / n2c2](https://portal.dbmi.hms.harvard.edu/) are subject to application and approval. Even though you are approved use these data in text analytics, there are restriction on showing individual notes to the public.

To get around the restrictions, we will use clinical notes at [mtsamples.com](https://www.mtsamples.com/). This website has a collection of 4999 sample clinical notes and these samples are "free to print, share, link, and distribute". 
