We compare the bags of words created with Amazon Comprehend Medical (amazon_me), medaCy (medacy_me), top 10 words of term frequency (top_tf) and term frequency inverse document frequency (top_tfidf) for three specialties: gastroenterology, neurology, and urology. The frequent words are visualized with wordcloud and barplot. Select from the dropdown list to compare two combinations of specialty and bag of words side by side.

### Results
**Amazon Comprehend Medical captures medical terms specific to medical specialty**: The most prominent words are organs such as colon, bowel, and abdomen in gastroenerology, brain and head in neurology, and bladder and prostate in urology. All of them are commonly examined in their respective medical specialties. The word "pain" appears in the top 10 of all three specialteis; it is not supprising that many patients felt pain of disearses. 

**medaCy focuses on words related to medication**: The word "vicryl" shows up as the number one words in gastroenterology and urology. Search it in the notes, we found that "Vicryl" was actually the brand name of a sutture used in surgey, while medaCy identified it as drug. Other than this error, most top words identified by medaCy are popular drugs such as fentanyl, aspirin in neurology, marcaine, and lidocaine. Another group of high frequency words related to how often the drugs are used, inluding daily, qd (Latin "quaque die", once a day), and p.o. (Latin "per os", by mouth). 

**Term frequency method picks more generic terms**: Top words picked by term frequency include gereric words like patient, procedure, and history. Some words replated to the specialty also show up, include colon, brain, andbladder. Interestingly, word left and right 
The top three are patient, procedure, and normal for gastoenterology and right, left, and patient for neurology. It is a bit strange why words right and left are among the top words in neurology and utology.

**tfidf method picks more specific words than the term frequency**: The top three are colon, scope, and gallbladder for gastroenterology, highly related to this medical specialty. The top three are temporal, activity, and cervical for neurology; the word temporal is associated with temporal lobe of the brain. Each of them only appears in less than 10 documents, not frequent words at all. The top three in urology are bladder, prostate, and inguinal, which are highly related to this specialty.